server:
  port: 8080

spring:
  application:
    name: smart-contract-demo
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/web3_demo
    username: postgres
    password: postgres

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.web3.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

web3j:
  rpc-url: https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID  # 改成自己的
  chain-id: 1  # 1=Mainnet, 56=BSC, 137=Polygon
  http-timeout: 60000
  websocket-timeout: 60000
  
  token:
    contract-address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"  # USDT合约
    contract-name: "USDT"
    start-block: latest
    polling-interval: 3000

