server:
  port: 8080

spring:
  application:
    name: smart-contract-demo
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:26655/ERC20
    username: antdb
    password: antdb

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.web3.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

web3j:
  # Sepolia 测试网 - 确保 RPC URL 和 chain-id 匹配
  rpc-url: https://sepolia.infura.io/v3/a2026a116984443d8efad00e5139d7aa
  chain-id: 11155111
  http-timeout: 60000
  websocket-timeout: 60000

  
  token:
    contract-address: "0x24EbA24F5Eaed8fC8B9Cc128deDAA9691244490F"
    contract-name: "JTK"
    start-block: latest
    polling-interval: 3000

